### PR TITLE
Fix flaky mesure.sh

### LINKED ISSUE #7: Occasional error in script
Every once in a while, the `measure.sh` scripts fails in an unrecoverable fashion, failing the whole job.

Here's an example run: https://github.com/camunda/zeebe/actions/runs/5388937809/jobs/9782417213?pr=13143

```
Run ./measure.sh
Waiting for minimal throughput
jq: error (at <stdin>:0): null (null) cannot be parsed as a number
Error: Process completed with exit code 5.
```

Since this is intermittent, even for the same PR, my guess is there's some race condition, and `null` is a possible early value for the call.

This is low severity, mostly just an annoying little thing.

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
This issue is likely caused by the request to the endpoint is happening before the information being available.

```
Waiting for minimal throughput
jq: error (at <stdin>:0): null (null) cannot be parsed as a number
Error: Process completed with exit code 5.
```

The error that we find in this script is that we are trying to parse a null value, the request-response body in this case.

One solution could be to increase the sleep timer before this request happens.
Another one that was used here is to retry the endpoint until the request-response body is no longer null.

Closes #7

### CODE REVIEW

File: measure.sh [hunk 1]
```diff
@@ -28,8 +28,14 @@ wait_for_query_value() {
 
     until [ "$result" -eq 1 ]
     do
-        sleep 30
-        value=$(curl -s $url -d "query=$1" -H "Authorization: Bearer $token" | jq '.data.result[0].value[1] | tonumber')
+        sleep 10
+        value=$(curl -s $url -d "query=$1" -H "Authorization: Bearer $token" | jq ' try .data.result[0].value[1] | tonumber')
+        until [ ! -z "$value" ]
```
Comment (npepinpe) [inline measure.sh:33]: :question: Can this loop forever? :smile: We have a timeout on the job in general, so it's probably fine I guess :shrug:

**Review by npepinpe — APPROVED** [review]
:rocket:

File: measure.sh (hunk 1 above)
Comment (rodrigo-lourenco-lopes) [reply measure.sh:33]: Humm perhaps having a limit it could be waiting is better, I will add that :)
